### ISSUE TITLE
Basic login page variation when authenticating from an OAuth application

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/oauth2#43]
Currently there's no difference when accessing the login page from a OAuth client request and the regular, basic authentication flow. Both forms are the same. 

As discussed in Desktop demo vol.3 an informative message could be shown when the login form is the entry point to get an authorization token for the clients. e.g.

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/27027364-6bd21fea-4f61-11e7-8dfe-fa6090378bbb.png"/>
</p>

cc/ @pmaier1 for final concept definition 

However, some can argue that the current authorization page is enough and displaying that same info in the login view is to duplicate stuff around: 

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/27026723-06918ce4-4f5f-11e7-83e6-1fb96860272f.png"/>
</p>

**Comment by Dagefoerde** [comment]
I think duplicating the login page is not very useful. The login page looks identical because it is the actual login page. This implies that you will see it only when you are not logged in in your given environment. This also implies that ownCloud is not going to issue a token just by logging in.
Your mockup message could well be understood as "OAuth application ... wants access to our username and password", since it already appears on the password page.

Anyway, pressing login is not going to issue a token by itself, so if you really want to display such a message during login, I would like to add something along the lines of my remark, too. Maybe
"The application will not get access to your password. You will be able to review the authorisation details on the next page" ... something to soothe your users. :)

But, if I remember correctly, other services do not include such information during login either, so I don't think it's necessary.

**Comment by tomneedham** [comment]
> Do you really like to authorize the application ...

Where is this string, we should change this to some better English?

**Comment by SamuAlfageme** [comment]
@tomneedham https://github.com/owncloud/oauth2/blob/master/templates/authorize.php#L28

**Comment by ogoffart** [comment]
Also related:  if the client may want to specify which username to use: https://github.com/owncloud/oauth2/issues/48

**Comment by pmaier1** [comment]
Generally I agree that there's no need to alter the login page for OAuth authorization. I kind of like the suggested hint but if we place it there it needs to be a little less technical: "The application 'Desktop Client' is requesting access to you account. To authorize it, please log in first.". 'Desktop Client' will be replacable if some other application - say Moodle - tries to authorize, right?

**Being logged in I see two viable options:**
1) Blank page displaying the authorization message centered
2) Login to files app with overlay modal displaying the authorization message centered and files app blurred in background

Both are fine, 2) would be kind of cooler.

**Suggestion for the authorization message:**

"**Do you want to authorize the application 'Application'?**
The application will gain access to your account and all of its contents. You can manage authorized applications in your personal settings."

Click on authorize/cancel redirects to files app / modal disappears.

**Question1:** I did not yet see an interface or something yet, so, can you manage authorized applications in personal settings?^^
**Question2:** Will a user be able to set a name for authorized applications? E.g. I want to authorize more than one desktop client -> "Desktop client notebook", "Desktop client PC" or something.

**Comment by Dagefoerde** [comment]
Q1: Yes, you can revoke authorisations that you made to your account from your personal settings page.
Q2: Authorisations are distinguished by client ID. Since ownCloud currently defines default client IDs per client type (desktop, android, ios), I think that you will be able to revoke clients by client type, but not by client instance. So you can revoke all desktop clients, but not a specific one.

**Comment by ogoffart** [comment]
@ Question2:  So far, no:  This is the name that is in the server database. (as filledchro in https://github.com/owncloud/oauth2/pull/38 )

**Comment by pmaier1** [comment]
Ok, thanks. So there's room for improvement in the future. Fine so far if a user can manage authorized applications and revoke by client type.
